name: Deploy Flutter Web App to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web App
        run: flutter build web --release

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          # Check if rsync is installed
          if ! command -v rsync &> /dev/null; then
            echo "rsync could not be found, installing..."
            sudo apt-get update && sudo apt-get install -y rsync
          fi

          # Deploy to the VPS using rsync
          rsync -avz --delete build/web/ $VPS_USER@$VPS_HOST:/var/www/admin.kacchibari.com
