name: Deploy Flutter Web App to VPS

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      -  name: Build Flutter web app
         run: flutter build web --release
      - name: Deploy to VPS
        run: |
          APP_DIR=/var/www/admin.kacchibari.com/html
          BUILD_DIR=build/web

          sudo rm -rf $APP_DIR/*
          sudo cp -r $BUILD_DIR/* $APP_DIR/

          # Set appropriate permissions
          sudo chown -R www-data:www-data $APP_DIR
          sudo chmod -R 755 $APP_DIR
