name: Deploy Flutter Web App to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web App
        run: flutter build web --release

      - name: Set up SSH key with ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS Host to known_hosts
        run: |
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          # Use rsync to copy the build/web directory to the VPS
          rsync -avz --delete build/web/ $VPS_USER@$VPS_HOST:/var/www/admin.kacchibari.com
