name: Deploy Flutter Web App to VPS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter test
        run: flutter test

      -  name: Build Flutter web app
         run: flutter build web --release

      - name: Deploy to VPS
        run: |
          rsync -avz --delete build/web/ zihad@kacchibari:/var/www/admin.kacchibari.com/

