name: Deploy Flutter Web App to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Debug Build Process
        run: |
          flutter --version
          flutter doctor
          flutter build web --release
          pwd && ls -l build/web

      - name: Deploy to VPS
        run: |
          sudo cp -r /home/runner/work/kacchi_bari_admin_dashboard/kacchi_bari_admin_dashboard/build/web/* /var/www/admin.kacchibari.com/html

